spring:
  application:
    name: euraka-server
server:
  port: 1111
eureka:
  instance:
    hostname: peer1
  client:
    service-url:
      defaultZone: http://peer2:1112/eureka/,http://peer3:1113/eureka