spring:
  application:
    name: euraka-server
server:
  port: 1113
eureka:
  instance:
    hostname: peer3
  client:
    service-url:
      defaultZone: http://peer1:1111/eureka/,http://peer2:1112/eureka